name: Bulid Spring Boot Project

on:
  push:
    branches:
      - main

jobs:
  bulid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
        
      - name: Bulid with Maven
        run: mvn clean install

      - name: Bulid Docker image
        run: echo "docker bulid -t my-spring-boot-app ."
      
      - name: Mock Docker Hub login
        run: echo "Docker Hub login"

      - name: Mock Docker Hub push
        run: echo "Docker image push to Docker Hub..."

  deploy:
    runs-on: ubuntu-latest
    needs: bulid

    steps:
      - name: Checkout code
        uses: sctions/checkout@v2

      - name: Mock deploy to server
        run: echo "Simulating de@loyment process..."
             echo "Pulling Docker image..."
             echo "Stopping existing container..."
             echo "Removing existing containar..."
             echo "Running new containar..."
